export * from "./getOffersPaging";
export * from "./getOfferById";
export * from "./deleteOffer";
export * from "./getInvoiceDiscount";
export * from "./getOffersItemsDropdown";
export * from "./getOffersCouponsDropdown";
export * from "./postOffersItemsDiscount";
export * from "./putOffersItemsDiscount";
export * from "./getOffersCustomers";
export * from "./postOffersCustomerDiscount";
export * from "./postOffersInvoiceDiscount";
export * from "./postOffersShippingDiscount";
export * from "./postOffersAddItemsByFilter";
export * from "./getCoupons"
export * from "./putOffersCustomerDiscount";
export * from "./putOffersExtraItemDiscount";
export * from "./putOffersInvoiceDiscount";
export * from "./putOffersItemsDiscountCustomers";
export * from "./putOffersShippingDiscount";
export * from "./types";
export * from "./offer-model";
export { GET as GetOffersPagingGET } from "./handler/getOffersPaging";
export { GET as GetCouponsGET } from "./handler/coupons";
export { GET as GetOfferByIdGET } from "./handler/getOfferById";
export { DELETE as DeleteOfferDELETE } from "./handler/deleteOffer";
export { GET as GetInvoiceDiscountGET } from "./handler/getInvoiceDiscount";
export { GET as GetOffersItemsDropdownGET } from "./handler/getOffersItemsDropdown";
export { GET as GetOffersCouponsDropdownGET } from "./handler/getOffersCouponsDropdown";
export { POST as PostOffersItemsDiscountPOST } from "./handler/postOffersItemsDiscount";
export { PUT as PutOffersItemsDiscountPUT } from "./handler/putOffersItemsDiscount";
export { GET as GetOffersCustomersGET } from "./handler/getOffersCustomers";
export { POST as PostOffersCustomerDiscountPOST } from "./handler/postOffersCustomerDiscount";
export { POST as PostOffersInvoiceDiscountPOST } from "./handler/postOffersInvoiceDiscount";
export { POST as PostOffersShippingDiscountPOST } from "./handler/postOffersShippingDiscount";
export { POST as PostOffersAddItemsByFilterPOST } from "./handler/postOffersAddItemsByFilter";
export { PUT as PutOffersCustomerDiscountPUT } from "./handler/putOffersCustomerDiscount";
export { PUT as PutOffersExtraItemDiscountPUT } from "./handler/putOffersExtraItemDiscount";
export { PUT as PutOffersInvoiceDiscountPUT } from "./handler/putOffersInvoiceDiscount";
export { PUT as PutOffersItemsDiscountCustomersPUT } from "./handler/putOffersItemsDiscountCustomers";
export { PUT as PutOffersShippingDiscountPUT } from "./handler/putOffersShippingDiscount";